#!/usr/bin/env python3
"""
generate-compose.py — reads sessions.json and generates docker-compose.sessions.yml

Usage:
    python3 scripts/generate-compose.py
    python3 scripts/generate-compose.py --output path/to/docker-compose.sessions.yml

Skips remote sessions (those with host != null).
"""

import json
import sys
import os
import argparse

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
RELAY_DIR = os.path.dirname(SCRIPT_DIR)

SESSIONS_FILE = os.path.join(RELAY_DIR, "sessions.json")

DEFAULT_OUTPUT = os.path.join(RELAY_DIR, "docker-compose.sessions.yml")


def sanitize_service_name(session_name: str) -> str:
    """Convert session name to a valid docker-compose service name."""
    return "session-" + session_name.replace("_", "-").lower()


def path_to_volume_name(path: str) -> str:
    """Convert a host path to a safe docker volume-label (for comments only)."""
    return path.replace("/", "-").lstrip("-")


def generate_compose(sessions: list, output_path: str) -> None:
    local_sessions = [s for s in sessions if s.get("host") is None]

    if not local_sessions:
        print("No local sessions found in sessions.json", file=sys.stderr)
        sys.exit(1)

    lines = [
        "# AUTO-GENERATED by scripts/generate-compose.py — do not edit by hand.",
        "# Regenerate with: python3 scripts/generate-compose.py",
        "#",
        "# Starts one container per local Claude session.",
        "# Each container runs mcp-server + claude-session-loop under s6-overlay.",
        "",
        "services:",
    ]

    for session in local_sessions:
        name = session["session"]
        thread_id = session["thread_id"]
        workdir = session["path"]
        svc = sanitize_service_name(name)

        lines.append(f"  {svc}:")
        lines.append(f"    image: relay-session:latest")
        lines.append(f"    build:")
        lines.append(f"      context: .")
        lines.append(f"      dockerfile: session.Dockerfile")
        lines.append(f"    container_name: relay-session-{name}")
        lines.append(f"    restart: always")
        lines.append(f"    env_file:")
        lines.append(f"      - .env")
        lines.append(f"    environment:")
        lines.append(f"      SESSION_NAME: \"{name}\"")
        lines.append(f"      TELEGRAM_THREAD_ID: \"{thread_id}\"")
        lines.append(f"      WORKDIR: \"{workdir}\"")

        # allowed_users passthrough if present
        if "allowed_users" in session:
            allowed = ",".join(str(u) for u in session["allowed_users"])
            lines.append(f"      ALLOWED_USERS: \"{allowed}\"")

        lines.append(f"    volumes:")
        lines.append(f"      # Shared queue between bot and session containers")
        lines.append(f"      - relay-queue:/tmp")
        lines.append(f"      # Claude credentials and global state")
        lines.append(f"      - /root/.claude:/root/.claude")
        lines.append(f"      # Project working directory")
        lines.append(f"      - {workdir}:{workdir}")
        lines.append(f"    depends_on:")
        lines.append(f"      - relay")
        lines.append(f"    logging:")
        lines.append(f"      driver: \"json-file\"")
        lines.append(f"      options:")
        lines.append(f"        max-size: \"10m\"")
        lines.append(f"        max-file: \"3\"")
        lines.append(f"    healthcheck:")
        lines.append(f"      test: [\"CMD\", \"pgrep\", \"-f\", \"claude\"]")
        lines.append(f"      interval: 30s")
        lines.append(f"      timeout: 10s")
        lines.append(f"      retries: 3")
        lines.append(f"      start_period: 30s")
        lines.append(f"")

    lines.append("volumes:")
    lines.append("  relay-queue:")
    lines.append("    external: true")
    lines.append("")

    content = "\n".join(lines)

    with open(output_path, "w") as f:
        f.write(content)

    print(f"Generated {output_path} with {len(local_sessions)} local sessions:")
    for s in local_sessions:
        print(f"  - {s['session']} (thread={s['thread_id']}, path={s['path']})")


def main():
    parser = argparse.ArgumentParser(description="Generate docker-compose.sessions.yml from sessions.json")
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="Output file path")
    parser.add_argument("--sessions", default=SESSIONS_FILE, help="sessions.json path")
    args = parser.parse_args()

    with open(args.sessions) as f:
        sessions = json.load(f)

    generate_compose(sessions, args.output)


if __name__ == "__main__":
    main()
