#!/usr/bin/env python3
"""
generate-compose.py — reads sessions.json and generates docker-compose files

Usage:
    python3 scripts/generate-compose.py           # local sessions only
    python3 scripts/generate-compose.py --remote  # also generate remote host compose files
    python3 scripts/generate-compose.py --output path/to/docker-compose.sessions.yml

Local sessions (host == null) → docker-compose.sessions.yml  (relay-session:latest, named volume)
Remote sessions (host != null) → docker-compose.remote-<HOST>.yml  (shaikeme/relay-session:latest, /tmp bind mount)
"""

import json
import sys
import os
import argparse

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
RELAY_DIR = os.path.dirname(SCRIPT_DIR)

SESSIONS_FILE = os.path.join(RELAY_DIR, "sessions.json")

DEFAULT_OUTPUT = os.path.join(RELAY_DIR, "docker-compose.sessions.yml")
REMOTE_IMAGE = "shaikeme/relay-sessions:latest"


def sanitize_service_name(session_name: str) -> str:
    """Convert session name to a valid docker-compose service name."""
    return "session-" + session_name.replace("_", "-").lower()


def path_to_volume_name(path: str) -> str:
    """Convert a host path to a safe docker volume-label (for comments only)."""
    return path.replace("/", "-").lstrip("-")


def _session_service_block(name: str, thread_id: int, workdir: str,
                           allowed_users: list | None,
                           image: str, tmp_volume: str,
                           depends_on_relay: bool,
                           with_build: bool = False,
                           session_type: str = "claude",
                           driver: str = "") -> list[str]:
    """Return lines for a single session service block."""
    svc = sanitize_service_name(name)
    dockerfile = "codex-session.Dockerfile" if session_type == "codex" else "session.Dockerfile"
    # healthcheck pgrep target differs by session type
    hc_process = "codex" if session_type == "codex" else "claude"
    # codex sessions need OpenAI credentials mounted; claude sessions need Claude credentials
    lines = []
    lines.append(f"  {svc}:")
    lines.append(f"    image: {image}")
    if with_build:
        lines.append(f"    build:")
        lines.append(f"      context: .")
        lines.append(f"      dockerfile: {dockerfile}")
    lines.append(f"    container_name: relay-session-{name}")
    lines.append(f"    restart: always")
    lines.append(f"    environment:")
    lines.append(f"      SESSION_NAME: \"{name}\"")
    lines.append(f"      TELEGRAM_THREAD_ID: \"{thread_id}\"")
    lines.append(f"      WORKDIR: \"{workdir}\"")
    if session_type == "codex":
        lines.append(f"      SESSION_TYPE: \"codex\"")
    if driver:
        lines.append(f"      SESSION_DRIVER: \"{driver}\"")
    if allowed_users:
        allowed = ",".join(str(u) for u in allowed_users)
        lines.append(f"      ALLOWED_USERS: \"{allowed}\"")
    lines.append(f"    volumes:")
    lines.append(f"      # Shared queue between bot and session containers")
    lines.append(f"      - {tmp_volume}:/tmp")
    lines.append(f"      # Relay env file for the MCP bridge only; do not inject bot creds into Claude/Codex")
    lines.append(f"      - /root/relay/.env:/root/relay/.env:ro")
    if session_type == "codex":
        lines.append(f"      # Codex credentials and config")
        lines.append(f"      - /root/.codex:/root/.codex")
    else:
        lines.append(f"      # Claude credentials and global state (directory + auth file)")
        lines.append(f"      - /root/.claude:/root/.claude")
        lines.append(f"      - /root/.claude.json:/root/.claude.json")
    lines.append(f"      # Docker socket — allows session to manage containers")
    lines.append(f"      - /var/run/docker.sock:/var/run/docker.sock")
    lines.append(f"      # Project working directory")
    lines.append(f"      - {workdir}:{workdir}")
    if depends_on_relay:
        lines.append(f"    depends_on:")
        lines.append(f"      - relay")
    lines.append(f"    logging:")
    lines.append(f"      driver: \"json-file\"")
    lines.append(f"      options:")
    lines.append(f"        max-size: \"10m\"")
    lines.append(f"        max-file: \"3\"")
    lines.append(f"    healthcheck:")
    lines.append(f"      test: [\"CMD\", \"pgrep\", \"-f\", \"{hc_process}\"]")
    lines.append(f"      interval: 30s")
    lines.append(f"      timeout: 10s")
    lines.append(f"      retries: 3")
    lines.append(f"      start_period: 30s")
    lines.append(f"")
    return lines


def generate_compose(sessions: list, output_path: str) -> None:
    local_sessions = [s for s in sessions if s.get("host") is None]

    if not local_sessions:
        print("No local sessions found in sessions.json", file=sys.stderr)
        sys.exit(1)

    lines = [
        "# AUTO-GENERATED by scripts/generate-compose.py — do not edit by hand.",
        "# Regenerate with: python3 scripts/generate-compose.py",
        "#",
        "# Starts one container per local session (Claude or Codex).",
        "# Each container runs mcp-server + session-loop under s6-overlay.",
        "",
        "services:",
    ]

    for session in local_sessions:
        stype = session.get("type", "claude")
        image = "relay-session-codex:latest" if stype == "codex" else "relay-session:latest"
        lines += _session_service_block(
            name=session["session"],
            thread_id=session["thread_id"],
            workdir=session["path"],
            allowed_users=session.get("allowed_users"),
            image=image,
            tmp_volume="relay-queue",
            depends_on_relay=True,
            with_build=True,
            session_type=stype,
            driver=session.get("driver", ""),
        )

    lines.append("volumes:")
    lines.append("  relay-queue:")
    lines.append("    external: true")
    lines.append("")

    content = "\n".join(lines)

    with open(output_path, "w") as f:
        f.write(content)

    print(f"Generated {output_path} with {len(local_sessions)} local sessions:")
    for s in local_sessions:
        print(f"  - {s['session']} (thread={s['thread_id']}, path={s['path']})")


def generate_remote_compose(sessions: list, host: str, output_path: str) -> None:
    """Generate a docker-compose file for session containers running on a remote host.

    Remote containers pull shaikeme/relay-session:latest from Docker Hub and
    bind-mount the host /tmp so the relay bot can write queue files via SSH.
    """
    remote_sessions = [s for s in sessions if s.get("host") == host]

    if not remote_sessions:
        print(f"No sessions for host {host}", file=sys.stderr)
        return

    short_host = host.split("@")[-1].replace(".", "-")
    lines = [
        f"# AUTO-GENERATED by scripts/generate-compose.py — do not edit by hand.",
        f"# Regenerate with: python3 scripts/generate-compose.py --remote",
        f"#",
        f"# Remote session containers for {host}.",
        f"# Deploy: scp this file + .env to {host}, then: docker compose -f <file> up -d",
        f"# /tmp is bind-mounted from the host so the relay bot can write queue files via SSH.",
        f"",
        f"services:",
    ]

    for session in remote_sessions:
        lines += _session_service_block(
            name=session["session"],
            thread_id=session["thread_id"],
            workdir=session["path"],
            allowed_users=session.get("allowed_users"),
            image=REMOTE_IMAGE,
            tmp_volume="/tmp",   # bind mount — SSH writes from relay bot land here
            depends_on_relay=False,
        )

    content = "\n".join(lines)

    with open(output_path, "w") as f:
        f.write(content)

    print(f"Generated {output_path} with {len(remote_sessions)} sessions for {host}:")
    for s in remote_sessions:
        print(f"  - {s['session']} (thread={s['thread_id']}, path={s['path']})")


def main():
    parser = argparse.ArgumentParser(description="Generate docker-compose files from sessions.json")
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="Output file path for local sessions")
    parser.add_argument("--sessions", default=SESSIONS_FILE, help="sessions.json path")
    parser.add_argument("--remote", action="store_true", help="Also generate compose files for remote hosts")
    args = parser.parse_args()

    with open(args.sessions) as f:
        sessions = json.load(f)

    generate_compose(sessions, args.output)

    if args.remote:
        remote_hosts = sorted({s["host"] for s in sessions if s.get("host")})
        for host in remote_hosts:
            short_host = host.split("@")[-1].replace(".", "-")
            remote_output = os.path.join(RELAY_DIR, f"docker-compose.remote-{short_host}.yml")
            generate_remote_compose(sessions, host, remote_output)


if __name__ == "__main__":
    main()
